//Escribe la barra lateral en el estilo styleblue.css
var sbar='<ul><li><div class="post2">Secciones</div><ul><li><a href="https://norfipc.com/index.html">Inicio</a></li><li><a href="https://norfipc.com/facebook/index.html">Para Facebook</a></li><li><a href="https://norfipc.com/amor/index.php">Para el Amor</a></li><li><a href="https://norfipc.com/mensajes-cristianos/index.php">Mensajes cristianos</a></li><li><a href="https://norfipc.com/articulos/index.html">Como lo hago</a></li><li><a href="https://norfipc.com/utiles/index.html">Modificar Windows</a></li><li><a href="https://norfipc.com/celulares/index.html">Celulares y tabletas</a></li><li><a href="https://norfipc.com/internet/index.html">Navegar en internet</a></li><li><a href="https://norfipc.com/redes-sociales/index.html">Redes sociales</a></li><li><a href="https://norfipc.com/descargas-gratis/index.html">Descargas gratis</a></li><li><a href="https://norfipc.com/redes/index.html">Redes inform&#225;ticas</a></li><li><a href="https://norfipc.com/virus/index.html">Virus y Malware</a></li><li><a href="https://norfipc.com/trucos/index.php">Trucos e Ideas</a></li><li><a href="https://norfipc.com/comandos/index.html">Comandos</a></li><li><a href="https://norfipc.com/inf/index.html">Informaciones varias</a></li><li><a href="https://norfipc.com/recuperar/index.html">Recuperar</a></li><li><a href="https://norfipc.com/registro/index.html">El Registro</a></li><li><a href="https://norfipc.com/infografia/index.html">Infograf&#237;as</a></li><li><a href="https://norfipc.com/web/index.html">Creaci&#243;n y dise&#241;o web</a></li><li><a href="https://norfipc.com/web/publicar-blog-sitio-web-servicios-internet.php">Publicaci&#243;n web</a></li><li><a href="https://norfipc.com/web/optimizar-mejorar-posicionamiento-web-buscadores.php">Posicionamiento web</a></li><li><a href="https://norfipc.com/codigos/index.php">C&#243;digos</a></li><li><a href="https://norfipc.com/herramientas/index.php">Herramientas web</a></li><li><a href="https://norfipc.com/leer/index.php">Leer</a></li><li><a href="https://norfipc.com/cuba/index.html">Conocer Cuba</a></li><li><a href="https://norfipc.com/fotos-naturaleza/index.php">Fotos de la naturaleza</a></li><li><a href="https://norfipc.com/about/index.php">Como lo hacemos</a></li></ul></li></ul><a href="https://norfipc.com/ultimas-publicaciones-del-sitio.php" target="_blank" title="P&#225;ginas y art&#237;culos m&#225;s recientes publicados en el sitio web NorfiPC">&#218;ltimas publicaciones del sitio</a><br><br><div id="qrcode"></div>';
document.getElementById('sidebar').innerHTML=sbar;
//Escribe Codigo QR
var dir=window.document.URL;
document.getElementById('qrcode').innerHTML='<img src="https://chart.googleapis.com/chart?chs=150x150&cht=qr&chl='+dir+'" width="150" height="150">';



